### ISSUE TITLE
Submitting editorials

### ISSUE THREAD

**Issue by MdAman02** [reyadussalahin/problem_solving#15] opened 2020-04-25 10:00 UTC
It's redundant to add problem descriptions in the editorial. It's enough to contain problem and contest link. Besides, this is an extra hassle to create formatting for problem descriptions which the OJ already has.
Make it simple. There may be a section for explaining the problem from the author's view.

**Comment by reyadussalahin** [comment] 2020-04-25 19:44
I understand this looks like a hassle right now and of course painful. I totally get it.

But one of the main goal of this repo was to be self contained, both in learning contents and editorials. It was expected that a lot of people would collaborate( it was intended to be a groups job...)

*but you know the rest.....*

Try as much as you can...and if you prefer not to add statements...its totally okay....i would still pull it....but try to add statements if you have time...even I don't add editorials to each problem of which i add soluion if i lack time...oh, and one more thing, eventually you'll get faster and it won't bother you...

Thanks for you collaboration. I would look forward to your next contribution.

P.S.: I am closing this issue.

**Closed by reyadussalahin** 2020-04-25 19:44 UTC
